source_mysql_settings:
  host: "192.168.198.239"
  port: 6666
  user: "admin"
  passwd: "123456"
  database: "test"
  charset: "utf8mb4"

source_server_id: 66661

binlog_file: "mysql-bin.000001"
binlog_pos: 4

# 可以根据需求取消以下注释并进行配置
#ignore_tables:
#  - "t1"
#  - "yy"

#ignore_prefixes:
#  - "^user_.*$"
#  - "^opt_.*$"

#repl_tables:
#  - "nba"

#repl_prefixes:
#  - "^rsz_.*$"

target_clickhouse_settings:
  host: "192.168.176.204"
  port: 9000
  user: "admin"
  password: "123456"
  database: "cktest"

# 如果需要设置ClickHouse集群名称，取消以下注释并修改相应值
#clickhouse_cluster_name: "perftest_1shards_3replicas"

LOG_FILE: "ck_repl_status.log"

